_BASE_: "mask_rcnn_R_50_FPN_3x_syncbn.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.12, 58.395]
  WEIGHTS: ""
  MASK_ON: True
  RESNETS:
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
SOLVER:
  IMS_PER_BATCH: 32
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  STEPS: (70000, 100000) 
  MAX_ITER: 120000 
  BASE_LR: 0.02
  MOMENTUM: 0.9
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001 
  WEIGHT_DECAY_BIAS: 0.0001 
  WEIGHT_DECAY_NORM: 0.0
TEST:
  EVAL_PERIOD: 5000
# NOTE: Please refer to Rethinking ImageNet Pre-training https://arxiv.org/abs/1811.08883
# to learn what you need for training from scratch.